### ISSUE TITLE
Popup on map markers - funky styling

### ISSUE THREAD

**Issue by darcyduke** [MITLibraries/MITlibraries-parent#126]
http://libraries.mit.edu/locations - click on a marker and the formatting of the content looks wonky. Not sure how long it's been like that.

**Comment by PBruk** [comment]
Pertinent files: locations.scss, page-main-locations.php...

**Comment by frrrances** [comment]
Looks like this is due to the clear: both on .content here: 

https://github.com/MITLibraries/MITlibraries-parent/blob/prod/css/partials/_layout.scss#L289

I think we can do without that line. @PBruk can you make a PR with that change and see if this gets fixed and the other things still work with it missing?
