### ISSUE TITLE
Fix line-height of HX elements

### ISSUE THREAD

**Issue by PBruk** [MITLibraries/MITlibraries-parent#137]
![preserve about digital](https://cloud.githubusercontent.com/assets/1832277/16240310/d919db9c-37b6-11e6-939e-cb608d657030.png)

The rule seems to be coming from Bootstrap `line-height: 1.1`

**Comment by matt-bernhardt** [comment]
@frrrances Can you confirm that this issue is now resolved? See attached screenshot, which shows http://libraries.mit.edu/preserve/about/digital/ 

![161108 header height](https://cloud.githubusercontent.com/assets/1403248/20111484/7ec51cba-a5b6-11e6-90b9-c51d7ee2b5e4.png)

FWIW, the title on this page is no longer a header - and is currently showing a line height of 1.4. I'm not sure whether making it a header would re-introduce this problem or not.

**Comment by matt-bernhardt** [comment]
![image](https://cloud.githubusercontent.com/assets/1403248/20111732/541389ec-a5b7-11e6-909f-621bcb03ae01.png)
Here is the corresponding page on -test, after making that text into an `h3` tag.

**Comment by frrrances** [comment]
👍

**Comment by matt-bernhardt** [comment]
Ok - I'm going to close this issue, and delete the associated branch.
