### ISSUE TITLE
edit help text on RSS page template

### ISSUE THREAD

**Issue by darcyduke** [MITLibraries/MITlibraries-parent#24]
In the special fields for RSS script  and RSS link the help text says to enter the full URL like so "http://libraries.mit.edu/rss_feeds/example.rss". Please change that text for both fields so that it does not include the protocol or the domain, like so: "/rss_feeds/example.rss" and "/rss_feeds/example.js"

**Comment by PBruk** [comment]
This gets changed in Custom Fields in the WP admin under RSS Page Attributes. All set in  -dev.

**Comment by matt-bernhardt** [comment]
So, this is something that doesn't require a code change in the theme - the change is made via the WP web interface?

**Comment by matt-bernhardt** [comment]
This was fixed without code changes using Advanced Custom Fields' interface. The `RSS Page Attributes` collection of custom fields now only lists the paths to the various scripts, rather than the domain. The values should be:

RSS Link:
Instructions: `Enter the path to the RSS feed, e.g. "/rss_feeds/example.rss"`
Default value: `/rss_feeds/example.rss`

RSS Script:
Instructions: `Paste the path to the RSS script here, e.g. "/rss_feeds/example.js"`
Default value: `/rss_feeds/example.js`

**Note**

This change assumes that we are not linking to other domains' RSS feeds. Should that assumption become incorrect, we should edit these values to specify either HTTPS or protocol-agnostic links.

**Comment by PBruk** [comment]
Sorry... just noticed this!

Yeah, the change is made in the WP admin... which took me a bit to figure
out. For some reason, I thought it was in some functions or /inc file.

Anyhoot. All set.


2016-01-04 15:17 GMT-05:00 Matthew Bernhardt <notifications@github.com>:

> So, this is something that doesn't require a code change in the theme -
> the change is made via the WP web interface?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MITLibraries/MITlibraries-parent/issues/24#issuecomment-168792262>
> .
>



-- 

"The reason is never the reason."


*- Some French Movie Director*"Every portrait that is painted with feeling
is a portrait of the artist, not the sitter."
*- Oscar Wilde*
