### ISSUE TITLE
Bump up local alert title to 18px

### ISSUE THREAD

**Issue by frrrances** [MITLibraries/MITlibraries-parent#40]
On the library location alerts, change the Alert title font-size from 16px to 18px, and bump the font-weight down to 400 to more closely match the site-wide alert.

**Comment by matt-bernhardt** [comment]
@PBruk and @frrrances - am I right in thinking that this will be only a stylesheet change? Or is it possible that a PHP template will be adjusted as well?

I ask because the code cleaning I'm doing for #42 is highly likely to change a large number of PHP templates, and I want to scope that work correctly to avoid merge conflicts with this fix.

**Comment by frrrances** [comment]
I would think just css but I'll let @PBruk chime in to confirm.

**Comment by PBruk** [comment]
Adjustment made, CSS only.

**Comment by frrrances** [comment]
@PBruk Did you adjust the font-weight as well?

**Comment by PBruk** [comment]
Okay, should be set now... for some reason, there was additional alert styling on another - unrelated - template that was affecting things. I removed and moved to _alerts.scss.
